"""add watermark selection

Revision ID: c918424cfe1d
Revises: d3cae9c478a4
Create Date: 2026-09-03 20:21:30.007700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c918424cfe1d'
down_revision: Union[str, Sequence[str], None] = 'd3cae9c478a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watermark_jobs',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('original_key', sa.String(length=500), nullable=False),
    sa.Column('mask_key', sa.String(length=500), nullable=True),
    sa.Column('result_key', sa.String(length=500), nullable=True),
    sa.Column('mode', sa.Enum('TEXT', 'CUSTOM', 'LOGO', name='watermarkmode'), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('selection', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'COMPLETED', 'FAILED', name='watermarkstatus'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watermark_jobs')
    # ### end Alembic commands ###
